### ISSUE TITLE
Replace __CONFIGURU_LEAF constant

### ISSUE THREAD

**Issue by smolijar** [AckeeCZ/configuru#33]
**Is your feature request related to a problem? Please describe.**

Configuru uses [`__CONFIGURU_LEAF`](https://github.com/AckeeCZ/configuru/search?q=__CONFIGURU_LEAF) attribute to detect bottom nodes of generic nested configuration object, which should be mapped via loaders. Since this is just a plain string, it's not encapsulated. Theoretically it could be provided by the users and result in unexpected behavior.

**Describe the solution you'd like**

Replace the string key constant with a symbol that will not be part of public API. Keep the existing functionality for runtime and types alike.

**Comment by DevanshCodes** [comment]
Can I work on this?

**Comment by grissius** [comment]
Sure
